schema: 'src/schema.graphql'
#schema: src/graphql.schema.json
#schema: '${HOST}/graphql'
documents: 'src/**/*.graphql'
#documents: 'src/**/*.ts'
include: ['src/**/*.graphql']
extensions:
  endpoints:
    default: http://localhost:4000
